### ISSUE TITLE
Printer panics if given a node with `nil` `Type`

### ISSUE THREAD

**Issue by masih** [ipld/go-ipld-prime#295]
A test panics when calling printer with a node for checking equality [at this line](https://github.com/ipld/go-ipld-prime/blob/master/printer/printer.go#L178).

In practice, can `Type` of a node be `nil`? If so, what should the printout look like?

```
=== RUN   TestUnionKeyedReset/union-using-embed/#00/type-create_and_repr-create_match
&{[{2 {} {{one}}} {2 {} {{two}}} {1 {three} {{}}}]}
<nil>
            --- FAIL: TestUnionKeyedReset/union-using-embed/#00/type-create_and_repr-create_match (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4260ee3]

goroutine 391 [running]:
testing.tRunner.func1.2({0x43a62c0, 0x4739270})
	/usr/local/opt/go/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/opt/go/libexec/src/testing/testing.go:1212 +0x218
panic({0x43a62c0, 0x4739270})
	/usr/local/opt/go/libexec/src/runtime/panic.go:1038 +0x215
github.com/ipld/go-ipld-prime/printer.(*printBuf).doString(0xc0000b7a50, 0x0, 0x0, {0x2d30d220, 0xc0003aa0f0})
	/Users/masih/Documents/work/pl/code/go-ipld-prime/printer/printer.go:181 +0x163
github.com/ipld/go-ipld-prime/printer.Config.Fprint({0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, 0x0, 0x0, ...}, ...)
	/Users/masih/Documents/work/pl/code/go-ipld-prime/printer/printer.go:55 +0x125
github.com/ipld/go-ipld-prime/printer.Config.Sprint(...)
	/Users/masih/Documents/work/pl/code/go-ipld-prime/printer/printer.go:46
github.com/ipld/go-ipld-prime/printer.Sprint({0x2d30d220, 0xc0003aa0f0})
	/Users/masih/Documents/work/pl/code/go-ipld-prime/printer/printer.go:26 +0xde
github.com/ipld/go-ipld-prime/node/tests.(*nodeContentEqualsChecker).Check(0xc000503d40, {0x2d3002c0, 0xc0003aa090}, {0xc00015e3e0, 0x4055089, 0x45433ce}, 0xc32)
	/Users/masih/Documents/work/pl/code/go-ipld-prime/node/tests/checkers.go:29 +0x7b
github.com/frankban/quicktest.check(0xc00030e2a0, {0xc0003aa150, {0x44882d8, 0x47725c0}, {0x2d3002c0, 0xc0003aa090}, {0xc00015e3e0, 0x1, 0x1}})
	/Users/masih/go/pkg/mod/github.com/frankban/quicktest@v1.14.0/quicktest.go:350 +0x864
github.com/frankban/quicktest.(*C).Check(0xc00030e2a0, {0x2d3002c0, 0xc0003aa090}, {0x44882d8, 0x47725c0}, {0xc00015e3e0, 0x1, 0x1})
	/Users/masih/go/pkg/mod/github.com/frankban/quicktest@v1.14.0/quicktest.go:189 +0x19a
github.com/frankban/quicktest.Check({0x44943b0, 0xc000503d40}, {0x2d3002c0, 0xc0003aa090}, {0x44882d8, 0x47725c0}, {0xc00015e3e0, 0x1, 0x1})
	/Users/masih/go/pkg/mod/github.com/frankban/quicktest@v1.14.0/quicktest.go:23 +0xc5
github.com/ipld/go-ipld-prime/node/tests.testcase.Test.func1.3(0x1)
	/Users/masih/Documents/work/pl/code/go-ipld-prime/node/tests/testcase.go:129 +0xba
testing.tRunner(0xc000503d40, 0xc0003aa120)
	/usr/local/opt/go/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:1306 +0x35a
```

[Build](https://github.com/ipld/go-ipld-prime/runs/4176265064?check_suite_focus=true).

**Comment by masih** [comment]
On a closer look test engine setup seems to panic [here](https://github.com/ipld/go-ipld-prime/blob/master/schema/gen/go/testEngine_plugin_test.go#L41) caused by: `plugin was built with a different version of package runtime/internal/sys`

**Comment by masih** [comment]
Big thanks to @mvdan for pointing this out: the root cause for this is an unimplemented case in test generators [here](https://github.com/ipld/go-ipld-prime/blob/e36330d430ab36ee264798a912d683fd0779b179/schema/gen/go/genMap.go#L141-L143)
