### ISSUE TITLE
bindnode cannot infer schemas with links

### ISSUE THREAD

**Issue by aschmahmann** [ipld/go-ipld-prime#321]
bindnode currently cannot infer schemas with links in them such as:

```
type Node struct {
   Next cidlink.Link
}

next := &Node{ Next: nextCid }
node := bindnode.Wrap(next, nil)
```

It will error with:
```
panic: duplicate type name: Link [recovered]
	panic: duplicate type name: Link

goroutine 55 [running]:
testing.tRunner.func1.2({0x18ccd60, 0xc000095f20})
	C:/Go/go1.17.5/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	C:/Go/go1.17.5/src/testing/testing.go:1212 +0x218
panic({0x18ccd60, 0xc000095f20})
	C:/Go/go1.17.5/src/runtime/panic.go:1038 +0x215
github.com/ipld/go-ipld-prime/schema.(*TypeSystem).Accumulate(0x28424e0, {0x1e4c498, 0xc0000a4be0})
	C:/Users/adin/go/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.4-0.20211217152141-008fd70fc96f/schema/tmpBuilders.go:151 +0x1b4
github.com/ipld/go-ipld-prime/node/bindnode.inferSchema({0x1e6db40, 0x1a3a1c0})
	C:/Users/adin/go/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.4-0.20211217152141-008fd70fc96f/node/bindnode/infer.go:318 +0x5f3
github.com/ipld/go-ipld-prime/node/bindnode.inferSchema({0x1e6db40, 0x1996140})
	C:/Users/adin/go/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.4-0.20211217152141-008fd70fc96f/node/bindnode/infer.go:303 +0x468
github.com/ipld/go-ipld-prime/node/bindnode.Wrap({0x189f960, 0xc000258090}, {0x0, 0x0})
	C:/Users/adin/go/pkg/mod/github.com/ipld/go-ipld-prime@v0.14.4-0.20211217152141-008fd70fc96f/node/bindnode/api.go:79 +0x1d9
...
```

What's going on is that `inferSchema` https://github.com/ipld/go-ipld-prime/blob/008fd70fc96f72514cbdf41a6fc5f76af0939dd8/node/bindnode/infer.go#L288 doesn't have any concept of Links.

We do have some types predefined already for what a Link could reasonably be, although we can also try interface detection to see if something fulfills the interface for an IPLD link. The ones we already have defined are https://github.com/ipld/go-ipld-prime/blob/008fd70fc96f72514cbdf41a6fc5f76af0939dd8/node/bindnode/infer.go#L20-L22

**Comment by mvdan** [comment]
Thanks for reporting - I'll fix this soon.
